name: "raylib ui preview"
on:
  push:
    branches:
      - master_cr
  workflow_dispatch:

env:
  UI_JOB_NAME: "Create raylib UI Report"
  REPORT_NAME: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master_cr' && 'master_cr' || 'default_report' }}
  SHA: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master_cr' && github.sha || github.sha }}
  MASTER_UI_BRANCH: ui_preview

jobs:
  preview:
    if: github.repository == 'crwusiz/openpilot'
    name: Preview & Save Screenshots
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      actions: read
    steps:
      - name: Waiting for ui generation to start
        run: sleep 90

      - name: Waiting for ui generation to end
        uses: lewagon/wait-on-check-action@v1.3.4
        with:
          ref: ${{ env.SHA }}
          check-name: ${{ env.UI_JOB_NAME }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-conclusions: success
          wait-interval: 20

      - name: Getting workflow run ID
        id: get_run_id
        run: |
          echo "run_id=$(curl https://api.github.com/repos/${{ github.repository }}/commits/${{ env.SHA }}/check-runs | jq -r '.check_runs[] | select(.name == "${{ env.UI_JOB_NAME }}") | .html_url | capture("(?<number>[0-9]+)") | .number')" >> $GITHUB_OUTPUT

      - name: Download raylib UI Artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          run_id: ${{ steps.get_run_id.outputs.run_id }}
          search_artifacts: true
          name: raylib-report-1-${{ env.REPORT_NAME }}
          path: ${{ github.workspace }}/pr_ui

      - name: Get ci-artifacts repository
        uses: actions/checkout@v4
        with:
          repository: crwusiz/ci-artifacts
          ssh-key: ${{ secrets.CI_ARTIFACTS_DEPLOY_KEY }}
          path: ${{ github.workspace }}/master_ui_raylib
          ref: ${{ env.MASTER_UI_BRANCH }}

      - name: Save new master_cr ui (Push to ci-artifacts)
        if: github.ref == 'refs/heads/master_cr' && github.event_name == 'push'
        working-directory: ${{ github.workspace }}/master_ui_raylib
        run: |
          MASTER_UI_BRANCH="${{ env.MASTER_UI_BRANCH }}"
          REPO="crwusiz/ci-artifacts"

          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)

          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git checkout ${MASTER_UI_BRANCH}

          git rm -rf .

          mv ${{ github.workspace }}/pr_ui/*.png .

          echo "# Raylib UI Screenshots: ${SHORT_SHA}" > README.md
          echo "This branch is automatically updated with raylib screenshots from the \`master_cr\` branch of \`crwusiz/openpilot\`." >> README.md
          echo "" >> README.md
          echo "## Latest Screenshots" >> README.md

          for file in *.png; do
            filename=$(basename "$file")
            url="https://raw.githubusercontent.com/${REPO}/${MASTER_UI_BRANCH}/${filename}"

            echo "---" >> README.md
            echo "### ${filename}" >> README.md
            echo "![${filename}](${url})" >> README.md
          done

          git add .
          git commit -m "raylib screenshots for commit ${SHORT_SHA} on master_cr"
          git push origin ${MASTER_UI_BRANCH} --force
          echo "README.md updated and pushed successfully to ${MASTER_UI_BRANCH}."

      - name: 🖼️ Generate Image Preview Summary
        if: github.ref == 'refs/heads/master_cr' && github.event_name == 'push'
        run: |
          MASTER_UI_BRANCH="ui_preview"
          REPO="crwusiz/ci-artifacts"

          echo "## ✅ New raylib UI Screenshots (master_cr)" >> $GITHUB_STEP_SUMMARY
          echo "Screenshots saved to [ui_preview](https://github.com/${REPO}/tree/${MASTER_UI_BRANCH}/README.md)" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY

          echo "<table border=\"0\">" >> $GITHUB_STEP_SUMMARY

          pushd ${{ github.workspace }}/pr_ui

          for file in $(find . -maxdepth 1 -name "*.png" -print | cut -c 3- | sort); do
            filename=$(basename "$file")
            url="https://raw.githubusercontent.com/${REPO}/${MASTER_UI_BRANCH}/${filename}"

            echo "<tr>" >> $GITHUB_STEP_SUMMARY
            echo "  <td align=\"center\" style=\"padding: 10px;\">" >> $GITHUB_STEP_SUMMARY
            echo "    <h4>${filename}</h4>" >> $GITHUB_STEP_SUMMARY
            echo "    <a href=\"${url}\" target=\"_blank\">" >> $GITHUB_STEP_SUMMARY
            echo "      <img src=\"${url}\" width=\"250\" alt=\"${filename}\">" >> $GITHUB_STEP_SUMMARY
            echo "    </a>" >> $GITHUB_STEP_SUMMARY
            echo "  </td>" >> $GITHUB_STEP_SUMMARY
            echo "</tr>" >> $GITHUB_STEP_SUMMARY
          done

          popd

          echo "</table>" >> $GITHUB_STEP_SUMMARY
